#!/bin/sh

# Command generated by arandr for configuring monitor resolutions and positioni
#
# --------
# |      |----
# |  4k  |   | 1080p
# |      |----
# --------


xrandr --output DVI-D-0 --mode 1920x1080 --pos 3840x540 --rotate normal \
  --output HDMI-1 --off \
  --output HDMI-0 --off \
  --output DP-3 --off \
  --output DP-2 --mode 3840x2160 --pos 0x0 --rotate normal \
  --output DP-1 --off \
  --output DP-0 --off
